service: cart-service
frameworkVersion: '3'

package:
  individually: true
  
provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-1
  iamRoleStatements:
  - Effect: Allow
    Action:
      - '*'
    Resource:
      - arn:aws:rds:us-east-1:166088341378:db:aws
  httpApi:
    cors:
      allowedOrigins: '*'
      allowCredentials: false
  environment:
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}


functions:
  cartApi:
    handler: src/main.handler
    events:
      - httpApi:
          method: ANY
          path: /
      - httpApi:
          method: ANY
          path: /{proxy+}
    vpc:
      securityGroupIds:
        - sg-07fd281db986c96f9
      subnetIds:
        - subnet-00b788058ab5b1598
        - subnet-04850051fb8d62f33
        - subnet-0eb468f64e020242c
        - subnet-0607e6fe9c91b5001
        - subnet-0c9d38e048db0d11c
        - subnet-0fe3df45a72412d08

# custom:
#   webpack:
#     webpackConfig: 'webpack.config.js' # Name of webpack configuration file
#     includeModules: true # Node modules configuration for packaging
#     packager: 'npm' # Packager that will be used to package your external modules
#     excludeFiles: src/**/*.test.js # Provide a glob for files to ignore

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-typescript
  - serverless-plugin-optimize
  - serverless-offline
  # - serverless-webpack